CREATE TABLE IF NOT EXISTS "user_new_maxhp" (
	"id"	integer NOT NULL,
	"account_id"	integer NOT NULL,
	"deleted"	integer NOT NULL DEFAULT '0',
	"name"	varchar(30) NOT NULL,
	"level"	integer NOT NULL,
	"exp"	integer NOT NULL,
	"genre_id"	integer NOT NULL,
	"race_id"	integer NOT NULL,
	"class_id"	integer NOT NULL,
	"home_id"	integer NOT NULL,
	"description"	varchar(255) DEFAULT NULL,
	"gold"	integer NOT NULL,
	"bank_gold"	integer NOT NULL DEFAULT '0',
	"free_skillpoints"	integer NOT NULL,
	"pets_saved"	integer NOT NULL DEFAULT '0',
	"spouse"	integer NOT NULL DEFAULT '0',
	"message_info"	varchar(512) DEFAULT '',
	"pos_map"	integer NOT NULL,
	"pos_x"	integer NOT NULL,
	"pos_y"	integer NOT NULL,
	"body_id"	integer NOT NULL,
	"head_id"	integer NOT NULL,
	"weapon_id"	integer NOT NULL,
	"helmet_id"	integer NOT NULL,
	"shield_id"	integer NOT NULL,
	"heading"	integer NOT NULL DEFAULT '3',
    "max_hp"	integer NOT NULL DEFAULT '18',
    "min_hp"	integer NOT NULL,
	"min_man"	integer NOT NULL,
	"min_sta"	integer NOT NULL,
	"min_ham"	integer NOT NULL,
	"min_sed"	integer NOT NULL,
	"killed_npcs"	integer NOT NULL DEFAULT '0',
	"killed_users"	integer NOT NULL DEFAULT '0',
	"invent_level"	integer NOT NULL DEFAULT '0',
	"is_naked"	integer NOT NULL DEFAULT '0',
	"is_poisoned"	integer NOT NULL DEFAULT '0',
	"is_incinerated"	integer NOT NULL DEFAULT '0',
	"is_dead"	integer NOT NULL DEFAULT '0',
	"is_sailing"	integer NOT NULL DEFAULT '0',
	"is_paralyzed"	integer NOT NULL DEFAULT '0',
	"is_silenced"	integer NOT NULL DEFAULT '0',
	"silence_minutes_left"	integer DEFAULT '0',
	"silence_elapsed_seconds"	integer DEFAULT '0',
	"is_mounted"	integer NOT NULL DEFAULT '0',
	"is_banned"	integer DEFAULT '0',
	"banned_by"	varchar(30) NOT NULL DEFAULT '',
	"ban_reason"	varchar(255) DEFAULT '',
	"counter_pena"	integer NOT NULL DEFAULT '0',
	"deaths"	integer NOT NULL DEFAULT '0',
	"ciudadanos_matados"	integer NOT NULL DEFAULT '0',
	"criminales_matados"	integer NOT NULL DEFAULT '0',
	"recibio_armadura_real"	integer NOT NULL DEFAULT '0',
	"recibio_armadura_caos"	integer NOT NULL DEFAULT '0',
	"recompensas_real"	integer DEFAULT '0',
	"recompensas_caos"	integer DEFAULT '0',
	"faction_score"	integer DEFAULT '0',
	"reenlistadas"	integer NOT NULL DEFAULT '0',
	"fecha_ingreso"	timestamp NOT NULL DEFAULT current_timestamp,
	"nivel_ingreso"	integer DEFAULT NULL,
	"matados_ingreso"	integer DEFAULT NULL,
	"status"	integer DEFAULT '0',
	"guild_index"	integer DEFAULT '0',
	"guild_aspirant_index"	integer DEFAULT NULL,
	"guild_rejected_because"	varchar(255) DEFAULT NULL,
	"chat_global"	integer DEFAULT '1',
	"chat_combate"	integer DEFAULT '1',
	"warnings"	integer NOT NULL DEFAULT '0',
	"elo"	integer NOT NULL DEFAULT '1000',
	"return_map"	integer NOT NULL DEFAULT '0',
	"return_x"	integer NOT NULL DEFAULT '0',
	"return_y"	integer NOT NULL DEFAULT '0',
	"last_logout"	integer NOT NULL DEFAULT 0,
	"is_locked_in_mao"	boolean DEFAULT 0,
	"is_logged"	boolean NOT NULL DEFAULT 0,
	"puntos_pesca"	INTEGER DEFAULT 0,
	"delete_code"	varchar(8) DEFAULT '',
	user_key varchar(128) DEFAULT '',
	is_reset int not null default 0, is_published integer DEFAULT 0, price_in_mao INTEGER DEFAULT 0,
	PRIMARY KEY("id" AUTOINCREMENT),
	UNIQUE("id","account_id","deleted"),
	CONSTRAINT "fk_user_account" FOREIGN KEY("account_id") REFERENCES "account"("id") ON DELETE CASCADE ON UPDATE CASCADE
);