Attribute VB_Name = "modMessageIDs"
' Argentum 20 Game Server
'
'    Copyright (C) 2025 Noland Studios LTD
'
'    This program is free software: you can redistribute it and/or modify
'    it under the terms of the GNU Affero General Public License as published by
'    the Free Software Foundation, either version 3 of the License, or
'    (at your option) any later version.
'
'    This program is distributed in the hope that it will be useful,
'    but WITHOUT ANY WARRANTY; without even the implied warranty of
'    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
'    GNU Affero General Public License for more details.
'
'    You should have received a copy of the GNU Affero General Public License
'    along with this program.  If not, see <https://www.gnu.org/licenses/>.
'
'    This program was based on Argentum Online 0.11.6
'    Copyright (C) 2002 Márquez Pablo Ignacio
'
'    Argentum Online is based on Baronsoft's VB6 Online RPG
'    You can contact the original creator of ORE at aaron@baronsoft.com
'    for more information about ORE please visit http://www.baronsoft.com/
'
'
'
Option Explicit
    
    
Public Const MSG_PARALYZED                                  As Integer = 1123
Public Const MSG_ALREADY_HIDDEN                             As Integer = 1127
Public Const MSG_CANNOT_HIDE_MOUNTED                        As Integer = 704
Public Const MSG_HIDE_FAILED                                As Integer = 57
Public Const MSG_TAME_FAILED                                As Integer = 659
Public Const MSG_MAP_NEWBIE_ONLY                            As Integer = 771
Public Const MSG_MAP_ONLY_CITIZENS                          As Integer = 772
Public Const MSG_MAP_ONLY_CRIMINALS                         As Integer = 773
Public Const MSG_MAP_REQUIRES_CLAN                          As Integer = 774
Public Const MSG_MAP_MIN_LEVEL                              As Integer = 1108
Public Const MSG_MAP_MAX_LEVEL                              As Integer = 1109
Public Const MSG_MAP_REQUIRES_GROUP                         As Integer = 775
Public Const MSG_MAP_REQUIRES_PATREON                       As Integer = 776
Public Const MSG_TILE_REQUIRES_PATREON                      As Integer = 776
Public Const MSG_PICKUP_UNAVAILABLE                         As Integer = 261

Public Const MSG_CLIENT_UPDATE_REQUIRED                        As Integer = 2092
Public Const MSG_INVALID_SESSION_TOKEN                         As Integer = 2093
Public Const MSG_CONNECTION_SLOT_ERROR                         As Integer = 2094
Public Const MSG_DISABLED_NEW_CHARACTERS                       As Integer = 1776
Public Const MSG_YOU_HAVE_TOO_MANY_CHARS                       As Integer = 1777
Public Const MSG_USERNAME_ALREADY_TAKEN                        As Integer = 1778
Public Const MSG_UPGRADE_ACCOUNT_TO_CREATE_MORE_CHARS          As Integer = 1779
Public Const MSG_RIDER_LEVEL_REQUIREMENT                       As Integer = 2078
Public Const MSG_CHARACTER_HOME                                As Integer = 2104
Public Const MSG_QUEST_LEVEL_REQUIREMENT                       As Integer = 1426
Public Const MSG_NPC_INMUNE_TO_SPELLS                          As Integer = 666
Public Const MSG_BLODIUM_ANVIL_REQUIRED                        As Integer = 2113
Public Const MSG_CANNOT_PICK_UP_ITEMS_IN_JAIL                  As Integer = 2109
Public Const MSG_CANNOT_DROP_ITEMS_IN_JAIL                     As Integer = 2110
Public Const MSG_CANNOT_TRADE_IN_JAIL                          As Integer = 2111
Public Const MSG_CANNOT_USE_HOME_IN_JAIL                       As Integer = 2112
Public Const MAP_HOME_IN_JAIL                                  As Integer = 66
Public Const MSG_QUEST_ALREADY_COMPLETED                       As Integer = 2114




' Msg2118 = Pay attention! You lost your net, it got caught on the special fish.
Public Const MSG_REMOVE_NET_LOST As Integer = 2118

' Msg2119 = Pay attention! You almost lost your net to the special fish.
Public Const MSG_REMOVE_NET_ALMOST_LOST As Integer = 2119

' Msg2120 = Pay attention! You almost lost your fishing rod to the special fish.
Public Const MSG_REMOVE_ALMOST_YOUR_FISHING As Integer = 2120

' Message IDs used for faction connection notifications (randomized variants).
Public Const MSG_CONNECTION_ROYAL_ARMY_1 As Integer = 2133
Public Const MSG_CONNECTION_ROYAL_ARMY_2 As Integer = 2134
Public Const MSG_CONNECTION_ROYAL_ARMY_3 As Integer = 2135
Public Const MSG_CONNECTION_ROYAL_ARMY_4 As Integer = 2136
Public Const MSG_CONNECTION_ROYAL_ARMY_5 As Integer = 2137
Public Const MSG_CONNECTION_ROYAL_ARMY_6 As Integer = 2138
Public Const MSG_CONNECTION_ROYAL_ARMY_7 As Integer = 2139
Public Const MSG_CONNECTION_ROYAL_ARMY_8 As Integer = 2140
Public Const MSG_CONNECTION_ROYAL_ARMY_9 As Integer = 2141
Public Const MSG_CONNECTION_ROYAL_ARMY_10 As Integer = 2142
Public Const MSG_CONNECTION_DARK_LEGION_1 As Integer = 2149
Public Const MSG_CONNECTION_DARK_LEGION_2 As Integer = 2150
Public Const MSG_CONNECTION_DARK_LEGION_3 As Integer = 2151
Public Const MSG_CONNECTION_DARK_LEGION_4 As Integer = 2152
Public Const MSG_CONNECTION_DARK_LEGION_5 As Integer = 2153
Public Const MSG_CONNECTION_DARK_LEGION_6 As Integer = 2154
Public Const MSG_CONNECTION_DARK_LEGION_7 As Integer = 2155
Public Const MSG_CONNECTION_DARK_LEGION_8 As Integer = 2156
Public Const MSG_CONNECTION_DARK_LEGION_9 As Integer = 2157
Public Const MSG_CONNECTION_DARK_LEGION_10 As Integer = 2158
Public Const MSG_PERFORATED_ARMOR As Integer = 2161
Public Const MSG_NPC_SPAWN_EVENT As Integer = 1548
Public Const MSG_NPC_EVENT_KILLED As Integer = 1549
Public Const MSG_ONLINE_RECORD_USERS As Integer = 1550
Public Const MSG_SERVER_USER_CONNECTED As Integer = 1706
Public Const MSG_USER_LEVEL_EXP As Integer = 1857
Public Const MSG_USER_HEALTH_MANA_STAMINA As Integer = 1858
Public Const MSG_USER_DAMAGE_WITH_WEAPON As Integer = 1859
Public Const MSG_USER_DAMAGE As Integer = 1860
Public Const MSG_USER_BODY_DEFENSE As Integer = 1861
Public Const MSG_USER_HEAD_DEFENSE As Integer = 1862
Public Const MSG_USER_INVENTORY_ITEM As Integer = 1865
Public Const MSG_TREASURE_EVENT_MAP_HINT As Integer = 1567
Public Const MSG_MAGIC_ITEM_EVENT_MAP_HINT As Integer = 1568
Public Const MSG_FOUND_TREASURE As Integer = 1639
Public Const MSG_FOUND_MAGIC_ITEM As Integer = 1640
Public Const MSG_NOW_BELONG_ROYAL_ARMY As Integer = 1932
Public Const MSG_EXPELLED_FROM_ROYAL_ARMY As Integer = 1933
Public Const MSG_EXPELLED_FROM_DARK_LEGION As Integer = 1934
Public Const MSG_NOW_BELONG_DARK_LEGION As Integer = 1935
Public Const MSG_BANK_ITEM_COUNT As Integer = 1939
Public Const MSG_BANK_ITEM_ENTRY As Integer = 1940
Public Const MSG_TRADE_CANCELLED As Integer = 1925
Public Const MSG_ITEM_MIN_LEVEL_REQUIRED As Integer = 1926
Public Const MSG_ITEM_MAX_LEVEL_ALLOWED As Integer = 1982
Public Const MSG_DIVORCE_NOTIFICATION As Integer = 1983
Public Const MSG_LOOT_BOX_OPENED As Integer = 1984
Public Const MSG_NPC_KILLED_BY_USER As Integer = 1986
Public Const MSG_RESURRECTION_ATTEMPT_NOTIFICATION As Integer = 1985
Public Const MSG_GLOBAL_QUEST_CONTRIBUTION_UPDATE As Integer = 2122
Public Const MSG_GLOBAL_QUEST_FINISHED As Integer = 2127
Public Const MSG_GLOBAL_QUEST_STARTED As Integer = 2128
Public Const MSG_CANNOT_EQUIP_NET_WITH_ROD As Integer = 2166

Public Const MSG_CAPTURE_EVENT_ALREADY_ACTIVE As Integer = 1008
Public Const MSG_CAPTURE_INVALID_INSCRIPTION_FEE As Integer = 1009
Public Const MSG_CAPTURE_MAX_PLAYERS_EXCEEDED As Integer = 1011
Public Const MSG_CAPTURE_INVALID_MIN_LEVEL As Integer = 1013
Public Const MSG_CAPTURE_MIN_LEVEL_GREATER_THAN_MAX As Integer = 1014
Public Const MSG_EVENTOS_EVENTO_FINALIZADO As Integer = 1563
Public Const MSG_LOBBY_INVALID_LEVEL_RANGE As Integer = 1607
Public Const MSG_LOBBY_MIN_LEVEL_GREATER_THAN_MAX As Integer = 1609
Public Const MSG_USUARIO_LANZANDO_HECHIZOS_EFECTIVIDAD_CASTEADOS_REVISAR As Integer = 1638
Public Const MSG_SERVIDOR_SIDO_ECHADO As Integer = 1641
Public Const MSG_FUNDADO_CLAN_ALINEACION As Integer = 1642
Public Const MSG_ACEPTADO_HONORABLE_CONSEJO_REAL_BANDERBILL As Integer = 1643
Public Const MSG_ACEPTADO_CONSEJO_LEGION_OSCURA As Integer = 1644
Public Const MSG_EXPULSADO_CONSEJO_REAL_BANDERBILL As Integer = 1645
Public Const MSG_EXPULSADO_CONSEJO_LEGION_OSCURA As Integer = 1646
Public Const MSG_BANNED_CLAN As Integer = 1647
Public Const MSG_SIDO_EXPULSADO_SERVIDOR As Integer = 1648
Public Const MSG_SUBASTANDO_CANTIDAD_PRECIO_INICIAL_MONEDAS_ESCRIBE_OFERTAR As Integer = 1649
Public Const MSG_OFERTA_MEJORADA_OFRECE_MONEDAS_ORO_TIEMPO_EXTENDIDO As Integer = 1650
Public Const MSG_SACERDOTE_CELEBRA_CASAMIENTO_ENTRE As Integer = 1651
Public Const MSG_EVENTOS_TODAVIA_NADIE_CAPAZ_ENCONTAR_TESORO_RECORDA As Integer = 1652
Public Const MSG_EVENTOS_NINGUN_VALIENTE_CAPAZ_ENCONTRAR_ITEM_MISTERIOSO As Integer = 1653
Public Const MSG_EVENTOS_TODAVIA_NADIE_LOGRO_MATAR_NPC_ENCUENTRA As Integer = 1654
Public Const MSG_SEGUNDOS As Integer = 1655
Public Const MSG_COUNTDOWN_GO As Integer = 1656
Public Const MSG_SERVIDOR_GRABANDO_PERSONAJES As Integer = 1657
Public Const MSG_SERVIDOR_PERSONAJES_GRABADOS As Integer = 1658
Public Const MSG_SERVIDOR_CERRANDO_SERVIDOR_LANZANDO_NUEVO_PARCHE As Integer = 1659
Public Const MSG_SERVIDOR As Integer = 1660
Public Const MSG_SERVIDOR_CERRANDO_SERVIDOR As Integer = 1661
Public Const MSG_QUEDAN_MINUTO_S_FINALIZAR_SUBASTA_ESCRIBE_SUBASTA As Integer = 1662
Public Const MSG_SUBASTA_CANCELADA_FALTA_OFERTAS As Integer = 1663
Public Const MSG_QUEDAN_MINUTO_S_FINALIZAR_SUBASTA_ESCRIBE_SUBASTA_1664 As Integer = 1664
Public Const MSG_QUEDAN_MINUTO_S_FINALIZAR_SUBASTA_ESCRIBE_SUBASTA_1665 As Integer = 1665
Public Const MSG_QUEDAN_MINUTO_S_FINALIZAR_SUBASTA_ESCRIBE_SUBASTA_1666 As Integer = 1666
Public Const MSG_QUEDAN_MINUTO_S_FINALIZAR_SUBASTA_ESCRIBE_SUBASTA_1667 As Integer = 1667
Public Const MSG_SUBASTA_TERMINADO_GANADOR As Integer = 1668
Public Const MSG_RETOS_VS_NINGUNO_PUDO_VENCER_RIVAL As Integer = 1670
Public Const MSG_RETOS_EQUIPO_VENCIO_EQUIPO_QUEDO_BOTIN_MONEDAS As Integer = 1671
Public Const MSG_RETOS_VENCIO_QUEDO_BOTIN_MONEDAS_ORO As Integer = 1672
Public Const MSG_EVENTO_ABIERTAS_INSCRIPCIONES_CARACTERISTICAS_NIVEL_ENTRE_INSCRIPTOS As Integer = 1674
Public Const MSG_EVENTO_CLASES_PARTICIPANTES_ESCRIBI_PARTICIPAR_INGRESAR_EVENTO As Integer = 1675
Public Const MSG_EVENTO_ELEGIDOS_PARTICIPAR_DAMOS_INICIO_EVENTO As Integer = 1676
Public Const MSG_EVENTOS_EVENTO_FINALIZADO_1677 As Integer = 1677
Public Const MSG_EVENTOS_CANCELADO_EVENTO_CAPTURA_BANDERA_FALTA_PARTICIPANTES As Integer = 1684
Public Const MSG_EVENTOS_EVENTO_CAPTURA_BANDERA_SIDO_CANCELADO_DEVUELTO As Integer = 1685
Public Const MSG_EVENTOS_EVENTO_CAPTURA_BANDERA_TERMINADO_EMPATE As Integer = 1686
Public Const MSG_EVENTOS_EVENTO_CAPTURA_BANDERA_TERMINADO_GANADOR_EQUIPO As Integer = 1687
Public Const MSG_EVENTOS_INICIADO_CAPTURA_BANDERA_PARTICIPANTES_PRECIO_INSCRIPCION As Integer = 1688
Public Const MSG_EMPEZANDO_CUENTA_REGRESIVA_SEGUNDOS As Integer = 1689
Public Const MSG_HAS_GANADO_PUNTOS_ELO As Integer = 1695
Public Const MSG_HAS_PERDIDO_PUNTOS_ELO As Integer = 1696
Public Const MSG_PARTICIPANTE_RETO_TIENE_NIVEL_MENOR_ELO_PERMANECE As Integer = 1697
Public Const MSG_SERVIDOR_BANEADO_DEBIDO_1699 As Integer = 1699
Public Const MSG_SERVIDOR_BANEADO_DEBIDO As Integer = 1700
Public Const MSG_SERVIDOR_BANEADO_CUENTA_DEBIDO As Integer = 1701
Public Const MSG_SERVIDOR_ECHO As Integer = 1702
Public Const MSG_SERVIDOR_DESBANEADO_CUENTA As Integer = 1703
Public Const MSG_CERRO_CLIENTE As Integer = 1704
Public Const MSG_BANEADO_DURANTE_PROXIMOS_DIAS_MEDIDA_TOMADA As Integer = 1705
Public Const MSG_EVENTOS_SEGUNDOS_CIERRAN_INSCRIPCIONES_EVENTO_CAPTURA_BANDERA As Integer = 1707
Public Const MSG_EVENTOS_CERRAMOS_INSCRIPCIONES As Integer = 1708
Public Const MSG_EVENTOS_EXTENDIERON_INSCRIPCIONES_FALTA_PARTICIPANTES As Integer = 1709
Public Const MSG_EVENTOS_SEGUNDOS_COMIENZA_RONDA As Integer = 1710
Public Const MSG_EVENTOS_RONDA_COMIENZA As Integer = 1711
Public Const MSG_EVENTOS_YAAA As Integer = 1712
Public Const MSG_EVENTOS_ATENCION_EQUIPO_TIENE_BANDERA_ENEMIGA_BASE As Integer = 1713
Public Const MSG_EVENTOS_EVENTO_CAPTURA_BANDERA_INICIADO As Integer = 1714
Public Const MSG_EVENTOS_EQUIPO_MUERTO_BATALLA As Integer = 1715
Public Const MSG_EVENTOS_ATENCION_EQUIPO_TOMADO_BANDERA_EQUIPO As Integer = 1716
Public Const MSG_EVENTOS_ATENCION_BANDERA_EQUIPO_SIDO_RECUPERADA As Integer = 1717
Public Const MSG_EVENTOS_ATENCION_BANDERA_EQUIPO_ENCUENTRA As Integer = 1718
Public Const MSG_EVENTOS_ATENCION_BANDERA_EQUIPO_ENCUENTRA_1719 As Integer = 1719
Public Const MSG_EVENTOS_RONDA_DARA_COMIENZO_SEGUNDOS As Integer = 1720
Public Const MSG_EVENTOS_EQUIPO_GANADO_RONDA As Integer = 1725
Public Const MSG_ESPERANDO_JUGADORES_PARTIDA_INICIARA_CUANDO_LLENE_SALA As Integer = 1727
Public Const MSG_MOMENTO_HAY_REQUIERE_MINIMO_PUEDA_INICIAR As Integer = 1728
Public Const MSG_EVENTO_CANCELADO_FALTA_JUGADORES As Integer = 1729
Public Const MSG_INICIE_CACERA As Integer = 1730
Public Const MSG_TENEMOS_GANADOR As Integer = 1731
Public Const MSG_WORLD_SAVE_NOTIFICATION As Integer = 1733
Public Const MSG_GLOBAL_CHAT_DISABLED As Integer = 1734
Public Const MSG_TREASURE_EVENT_ALREADY_ACTIVE_MAP_HINT As Integer = 1735
Public Const MSG_MAGIC_ITEM_EVENT_ALREADY_ACTIVE_MAP_HINT As Integer = 1736
Public Const MSG_NPC_EVENT_ALREADY_ACTIVE_MAP_HINT As Integer = 1737
Public Const MSG_EVENTOS_EVENTO_SIDO_CANCELADO As Integer = 1738
Public Const MSG_NO_ENCONTRO_NINGUN_EVENTO_ACTIVO As Integer = 1739
Public Const MSG_SERVIDOR_CERRANDO_AHORA As Integer = 1740
Public Const MSG_SERVIDOR_TIMER_LLUVIA As Integer = 1741
Public Const MSG_OTORGADO As Integer = 1743
Public Const MSG_PUNTOS As Integer = 1744
Public Const MSG_SIDO_BANEADO_SISTEMA_ANTI_CHEATS As Integer = 1746
Public Const MSG_NPC_SPAWN_FAILED As Integer = 1786
Public Const MSG_SERVIDOR_CONCLUIDO_SENTENCIA_BAN As Integer = 1787
Public Const MSG_VUELTO_MUNDO As Integer = 1788
Public Const MSG_CLAN_GANADO_PUNTOS_EXPERIENCIA As Integer = 1789
Public Const MSG_CLAN_SUBIDO_NIVEL_NUEVOS_BENEFICIOS_DISPONIBLES As Integer = 1790
Public Const MSG_NO_PUDO_SPAWNEAR_NPC_REVISAR As Integer = 1792
Public Const MSG_CLAN_MARCO As Integer = 1798
Public Const MSG_NO_PUEDEN_ACTUALIZAR_RELACIONES As Integer = 1799
Public Const MSG_CLAN_FIRMADO_PAZ As Integer = 1800
Public Const MSG_RELACIONES_CLAN_DESACTIVADAS_MOMENTO As Integer = 1801
Public Const MSG_CLAN_RECHAZADO_PROPUESTA_ALIANZA As Integer = 1802
Public Const MSG_RECHAZADO_NUESTRA_PROPUESTA_ALIANZA_CLAN As Integer = 1803
Public Const MSG_CLAN_RECHAZADO_PROPUESTA_PAZ As Integer = 1804
Public Const MSG_RECHAZADO_NUESTRA_PROPUESTA_PAZ_CLAN As Integer = 1805
Public Const MSG_CLAN_FIRMADO_ALIANZA As Integer = 1806
Public Const MSG_CLAN_ENTRADO_GUERRA As Integer = 1807
Public Const MSG_DECLARA_GUERRA_CLAN As Integer = 1808
Public Const MSG_SIDO_ACEPTADO_MIEMBRO_CLAN As Integer = 1809
Public Const MSG_EXPULSADO_CLAN As Integer = 1810
Public Const MSG_DEJA_CLAN As Integer = 1811
Public Const MSG_CONSEJO As Integer = 1812
Public Const MSG_CONCILIO As Integer = 1813
Public Const MSG_ARMADA_REAL As Integer = 1815
Public Const MSG_FUERZAS_CAOS As Integer = 1816
Public Const MSG_SIDO_EXPULSADO_CLAN_ADMINISTRADORES_SERVIDOR As Integer = 1817
Public Const MSG_CLAN_SOLICITA_APOYO_CLAN_PUEDES_VER_UBICACION As Integer = 1818
Public Const MSG_CACERA_INICIARA As Integer = 1819
Public Const MSG_ACABA_TIEMPO As Integer = 1820
Public Const MSG_MAPA_CERRARA_SEGUNDOS As Integer = 1821
Public Const MSG_QUEDAN_MINUTOS As Integer = 1822
Public Const MSG_PUNTOSA As Integer = 1823
Public Const MSG_PUNTOS_1824 As Integer = 1824
Public Const MSG_PREGUNTA_ROL As Integer = 1825
Public Const MSG_RECIBIDO_NUEVA_DENUNCIA_PARTE As Integer = 1826
Public Const MSG_ADMINISTRACION_SILENCIADO_OFFLINE_MINUTOS As Integer = 1827
Public Const MSG_ADMINISTRACION_DESILENCIADO_OFFLINE As Integer = 1828
Public Const MSG_ADMINISTRACION_SILENCIADO_MINUTOS As Integer = 1829
Public Const MSG_ADMINISTRACION_DESILENCIADO As Integer = 1830
Public Const MSG_ADVERTIDO As Integer = 1831
Public Const MSG_EJECUTADO As Integer = 1832
Public Const MSG_TRASLADADO_USUARIO_MAPA As Integer = 1833
Public Const MSG_ADMINISTRACION_CAMBIO_NOMBRE_USUARIO As Integer = 1834
Public Const MSG_SERVIDOR_CHAT_GENERAL_HABILITADO_ESCRIBE_CONSOLA_MENSAJE As Integer = 1835
Public Const MSG_RECIBIDO_NUEVO_MENSAJE_SOPORTE As Integer = 1836
Public Const MSG_SERVIDOR_EVENTO_FACCIONARIO As Integer = 1837
Public Const MSG_POSICIONES As Integer = 1838
Public Const MSG_EQUIPO As Integer = 1839
Public Const MSG_GANADOR_EQUIPO As Integer = 1840
Public Const MSG_NO_PODES_BANEARTE_VOS_MISMO As Integer = 1841
Public Const MSG_PERSONAJE_NO_EXISTE As Integer = 1842
Public Const MSG_USUARIO_ENCUENTRA_BANEADO As Integer = 1843
Public Const MSG_COMERCIO_CANCELADO_OTRO_USUARIO As Integer = 1844
Public Const MSG_TOCADO_PARTICIPAR_EQUIPO_DEBERAS_PROTEGER_COMPANEROS_EQUIPO As Integer = 1845
Public Const MSG_VOLVERAS_BASE_SEGUNDOS As Integer = 1846
Public Const MSG_HAS_RECUPERADO_INSCRIPCION_GANADO_MONEDAS_ORO_ADICIONALES As Integer = 1847
Public Const MSG_INGRESAR_EVENTO_DEBERAS_SER_NIVEL As Integer = 1848
Public Const MSG_INGRESAR_EVENTO_NIVEL_NO_PUEDE_SER_MAYOR As Integer = 1849
Public Const MSG_QUIERE_TRANSPORTARSE_UBICACION_ESCRIBE_SUM_TRAERLO As Integer = 1850
Public Const MSG_TRANSPORTADO_HACIA_DONDE_ENCUENTRAS As Integer = 1851
Public Const MSG_RESUCITADO As Integer = 1853
Public Const MSG_CURADO As Integer = 1854
Public Const MSG_QUIERE_TRANSPORTARTE_UBICACION_ESCRIBE_IRA_IR As Integer = 1855
Public Const MSG_TRANSPORTADO As Integer = 1856
Public Const MSG_NO_TIENE_OBJETOS As Integer = 1867
Public Const MSG_NO_TIENE_ORO As Integer = 1868
Public Const MSG_INVISIBILIDAD_NO_TIENE_EFECTO As Integer = 1869
Public Const MSG_ENVENENADO_HECHIZO_NO_TUVO_EFECTO As Integer = 1870
Public Const MSG_NO_PUEDE_VOLVER_SER_PARALIZADO_TAN_RAPIDO As Integer = 1872
Public Const MSG_NO_PUEDE_VOLVER_SER_INMOVILIZADO_TAN_RAPIDO As Integer = 1873
Public Const MSG_INTENTANDO_REVIVIRTE_DESACTIVA_SEGURO_RESURRECCION_PERMITIRLE_HACERLO As Integer = 1874
Public Const MSG_HAS_RESTAURADO_PUNTOS_HAMBRE As Integer = 1875
Public Const MSG_ABORDAJE_INICIARA As Integer = 1880
Public Const MSG_ACABO_TIEMPO As Integer = 1881
Public Const MSG_MAPA_CERRARA As Integer = 1882
Public Const MSG_MARINEROS_ABORDAJE As Integer = 1883
Public Const MSG_QUEDAN_MINUTOS_1884 As Integer = 1884
Public Const MSG_TENEMOS_GANADOR_1889 As Integer = 1889
Public Const MSG_MATANZA_INICIARA_MINUTOS As Integer = 1890
Public Const MSG_INICIE_MASACRE As Integer = 1893
Public Const MSG_QUEDAN_MINUTOS_1894 As Integer = 1894
Public Const MSG_RESTAURADO_PUNTOS_HAMBRE As Integer = 1895
Public Const MSG_HAS_RESTAURADO_PUNTOS_HAMBRE_1896 As Integer = 1896
Public Const MSG_HAS_QUITADO_PUNTOS_HAMBRE As Integer = 1897
Public Const MSG_QUITADO_PUNTOS_HAMBRE As Integer = 1898
Public Const MSG_HAS_QUITADO_PUNTOS_HAMBRE_1899 As Integer = 1899
Public Const MSG_HAS_RESTAURADO_PUNTOS_SED As Integer = 1900
Public Const MSG_RESTAURADO_PUNTOS_SED As Integer = 1901
Public Const MSG_HAS_RESTAURADO_PUNTOS_SED_1902 As Integer = 1902
Public Const MSG_HAS_QUITADO_PUNTOS_SED As Integer = 1903
Public Const MSG_QUITADO_PUNTOS_SED As Integer = 1904
Public Const MSG_HAS_QUITADO_PUNTOS_SED_1905 As Integer = 1905
Public Const MSG_HAS_RESTAURADO_PUNTOS_MANA As Integer = 1907
Public Const MSG_RESTAURADO_PUNTOS_MANA As Integer = 1908
Public Const MSG_HAS_RESTAURADO_PUNTOS_MANA_1909 As Integer = 1909
Public Const MSG_HAS_QUITADO_PUNTOS_MANA As Integer = 1910
Public Const MSG_QUITADO_PUNTOS_MANA As Integer = 1911
Public Const MSG_HAS_QUITADO_PUNTOS_MANA_1912 As Integer = 1912
Public Const MSG_HAS_RESTAURADO_PUNTOS_VITALIDAD As Integer = 1913
Public Const MSG_RESTAURADO_PUNTOS_VITALIDAD As Integer = 1914
Public Const MSG_HAS_RESTAURADO_PUNTOS_VITALIDAD_1915 As Integer = 1915
Public Const MSG_HAS_QUITADO_PUNTOS_VITALIDAD As Integer = 1916
Public Const MSG_QUITADO_PUNTOS_VITALIDAD As Integer = 1917
Public Const MSG_HAS_RESTAURADO_PUNTOS_VIDA As Integer = 1918
Public Const MSG_RESTAURADO_PUNTOS_VIDA As Integer = 1919
Public Const MSG_HAS_RESTAURADO_PUNTOS_VIDA_1920 As Integer = 1920
Public Const MSG_HAS_CAUSADO_PUNTOS_DANO As Integer = 1921
Public Const MSG_HAS_RESTAURADO_PUNTOS_VIDA_1922 As Integer = 1922
Public Const MSG_RESTAURADO_PUNTOS_VIDA_1923 As Integer = 1923
Public Const MSG_ENVENENADO As Integer = 1924
Public Const MSG_ATACO_FALLO As Integer = 1930
Public Const MSG_NO_TIENES_ESA_CANTIDAD_DISPONIBLE_AGREGAR As Integer = 1936
Public Const MSG_NECESITAS_CLAN_PERTENECER_MAPA As Integer = 1941
Public Const MSG_CONECTADO As Integer = 1942
Public Const MSG_DEJAS_ESCUCHAR As Integer = 1943
Public Const MSG_ERROR_CLAN_NO_EXISTE As Integer = 1944
Public Const MSG_PERSONAJE_NO_EXISTE_ELIMINADO_LISTA_MIEMBROS As Integer = 1945
Public Const MSG_NO_PERTENECES_NINGUN_CLAN As Integer = 1946
Public Const MSG_NO_ERES_LIDER_CLAN As Integer = 1947
Public Const MSG_PERSONAJE_NO_NI_ASPIRANTE_NI_MIEMBRO_CLAN As Integer = 1948
Public Const MSG_DEJADO_COMERCIAR_VOS As Integer = 1949
Public Const MSG_RECHAZADO_OFERTA As Integer = 1950
Public Const MSG_CAMBIADO_OFERTA As Integer = 1951
Public Const MSG_DESEA_CASARSE_CONTIGO_PERMITIRLO_HAZ_CLICK_SACERDOTE As Integer = 1956
Public Const MSG_TIEMPO_RESTANTE_MINUTO_S As Integer = 1957
Public Const MSG_APUESTA_MINIMA_MONEDAS_ORO As Integer = 1958
Public Const MSG_NO_PUEDES_JUGAR_RETOS_ADMINISTRADORES As Integer = 1959
Public Const MSG_NO_CONECTADO As Integer = 1960
Public Const MSG_NO_INVITADO_NINGUN_RETO_SIDO_CANCELADO As Integer = 1961
Public Const MSG_NECESITAS_MONEDAS_ORO_ACEPTAR_RETO As Integer = 1962
Public Const MSG_TIENES_DEMASIADAS_POCIONES_ROJAS_CANTIDAD_MAXIMA As Integer = 1963
Public Const MSG_HAS_ACEPTADO_RETO As Integer = 1964
Public Const MSG_RETO_SIDO_CANCELADO As Integer = 1965
Public Const MSG_OTORGAS_MONEDAS_ORO_POZO_RETO As Integer = 1966
Public Const MSG_COMENZADO_RETO As Integer = 1967
Public Const MSG_ADMITIR_DERROTA_ESCRIBE_ABANDONAR As Integer = 1968
Public Const MSG_COMIENZA_RONDA_N As Integer = 1969
Public Const MSG_RONDA As Integer = 1970
Public Const MSG_AGOTADO_TIEMPO_RETO As Integer = 1971
Public Const MSG_TIENES_MINUTO_LEVANTAR_ITEMS_PISO As Integer = 1972
Public Const MSG_HAS_ABANDONADO_RETO As Integer = 1973
Public Const MSG_ENCUENTRAS_RETO As Integer = 1974
Public Const MSG_NO_PUEDES_ACCEDER_RETO_CONSULTA As Integer = 1975
Public Const MSG_NO_PUEDES_JUGAR_RETO_ESTANDO_EVENTO As Integer = 1976
Public Const MSG_NO_PUEDES_PARTICIPAR_RETO_MAPA_INSEGURO As Integer = 1977
Public Const MSG_NO_PUEDES_IR_RETO_PARTICIPAS_TORNEO As Integer = 1978
Public Const MSG_ENCARCELADO As Integer = 1979
Public Const MSG_GROUP_GOLD_REWARD As Integer = 1980
Public Const MSG_EXPULSADO_FORMA_DEFINITIVA_FUERZAS_REALES As Integer = 1989
Public Const MSG_EXPULSADO_FUERZAS_REALES_PROHIBIDA_REENLISTADA As Integer = 1990
Public Const MSG_EXPULSADO_FORMA_DEFINITIVA_FUERZAS_CAOS As Integer = 1991
Public Const MSG_EXPULSADO_FUERZAS_CAOS_PROHIBIDA_REENLISTADA As Integer = 1992
Public Const MSG_USER_GUILD_TAG As Integer = 1993
Public Const MSG_VOLVERAS_HOGAR_SEGUNDOS As Integer = 1994
Public Const MSG_DEBES_ESTAR_MUERTO_PODER_UTILIZAR_COMANDO As Integer = 1995
Public Const MSG_HAS_REGRESADO_CIUDAD_ORIGEN As Integer = 1996
Public Const MSG_NO_TIENES_ESA_CANTIDAD_DISPONIBLE_AGREGAR_1997 As Integer = 1997
Public Const MSG_NO_TIENES_SUFICIENTE_LUGAR_AGREGAR_ESA_CANTIDAD As Integer = 1998
Public Const MSG_NO_TIENES_ESA_CANTIDAD As Integer = 1999
Public Const MSG_SUCCESFULLY_RETURN_TO_HOME_CITY = 1065
Public Const MSG_SUCCESFULLY_TELEPORTED = 1066
Public Const MSG_INVALID_RUNE = 2080
Public Const MSG_NOT_USABLE_INSIDE_MESON = 2081
Public Const MSG_INVALID_FAST_TRAVEL_MAP_ORIGIN = 2162
Public Const MSG_MESSAGE_RECEIVED = 1187
Public Const MSG_MESSAGE_SENT = 1188
Public Const MSG_QUESTION_ANSWERED = 2169
